version: '3.8'
services:
  mysqldb:
    image: mysql:8.0.26
    container_name: airj18_db
    restart: always
    # env_file: 
    #   - ./.env
    environment:
      MYSQL_DATABASE: airtnt
      MYSQL_ROOT_PASSWORD: 123456
      # - MYSQL_USER=root
      # - MYSQL_PASSWORD=123456
      # - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3307:3306
    # healthcheck:
    #   test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
    #   timeout: 20s
    #   retries: 5
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  app:
    image: skqist225/airj18
    depends_on:
      - mysqldb
        # condition: service_healthy
    # build: ./Backend
    container_name: airj18_app
    restart: on-failure
    # env_file: 
    #   - ./.env
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_PORT: 3306
      # SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/airtnt?createDatabaseIfNotExist=true
      # SPRING_DATASOURCE_USERNAME: root
      # SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - 9090:8080
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    networks:
      - backend

volumes:
  db:

networks:
  backend: 

